set -g prefix C-j
bind C-j next-window
bind C-q select-window -t 1
bind C-w select-window -t 2
bind C-e select-window -t 3

set -g status-bg "#7f7f7f"

setw -g mode-keys       vi
set  -g base-index      1
setw -g pane-base-index 1
